Allow Job body to be "anything" (Vec<u8> instead of String)
iFaceless/beanstalkc-rust pull request #5
Opened 2020-09-27 22:05 UTC by maxleiko

First of all, thanks for the amazing work on this Beanstalkd client.

I was about to use it for a project but I needed Jobs to be able to handle raw bytes payloads (not just utf-8 encoded strings).
Long story short, we send gzipped payload (that might not be all utf-8 chars), which lead to Utf8Error [in the automatic conversion](https://github.com/iFaceless/beanstalkc-rust/blob/master/src/request.rs#L53).
We can argue this choice, but we could also give the choice to the library users, with this pull request :)

So, this is a slight modification of the API:
```rust
pub struct Job<'a> {
    // ...
    body: Vec<u8>, // instead of String
    // ...
}

// and the impacted bits here and there, mainly:

impl<'a> Job<'a> {
    // ...
    /// Return job body.
    pub fn body(&self) -> &[u8] {
        &self.body[..]
    }

    /// Return job body as UTF-8 `&str`  
    /// This method is just calling `std::str::from_utf8(&self.body)`
    pub fn body_utf8(&self) -> BeanstalkcResult<&str> {
        Ok(str::from_utf8(&self.body)?)
    }
   // ...

  // and some other stuff
```
I'm pretty sure you don't want to merge this as-is, so feel free to ask for modifications.﻿

2020-10-01 13:06 UTC, iFaceless requested changes

2020-10-01 13:06 UTC, iFaceless commented on src/job.rs
> +    pub fn body_utf8(&self) -> BeanstalkcResult<&str> {
Hi, maybe we can just remove `body_utf8`? `str:from_utf8(job.body().to_vec())` or `str::from_utf8_lossy(job.body())` just works. User can choose a proper method to decode the job payload. :)

2020-10-01 13:16 UTC, iFaceless commented
Hey, thanks for your contribution! And I'm glad to know that this a helpful crate to your project. I think it's nessary to be able to handle job body with raw bytes payload.

2020-10-01 13:38 UTC, maxleiko commented
> Hey, thanks for your contribution! And I'm glad to know that this a helpful crate for your project. I think it's nessary to be able to handle job body with raw bytes payload.

There you go

2020-10-02 03:40 UTC, merged

2020-10-02 04:11 UTC, iFaceless commented
Hi, thanks again. Version bumped to 1.0.0, and I've already declared that version 1.0.0 introduced a breaking change in README.